import navegacaoTab from "./modules/navegacaotab.js";
import navegacaoAccordion from "./modules/navegacaoaccordion.js";
import scrollSuave from "./modules/scrollsuave.js";
import efeitoScroll from "./modules/scrollefeito.js";
import modal from "./modules/modal.js";
import tooltip from "./modules/tooltip.js";
import menu from "./modules/menu.js";
import menuMobile from "./modules/menuMobile.js";
import horario from "./modules/horario.js";
import animais from "./modules/fetchAnimais.js";
import btc from "./modules/btc.js";

navegacaoTab();
navegacaoAccordion();
scrollSuave();
efeitoScroll();
modal();
tooltip();
menu();
menuMobile();
horario();
animais();
btc();
